### ISSUE TITLE
Feature Request: support dovecot IMAP keyword flags

### ISSUE THREAD

**Issue by njh** [ktheory/maildir#26]
Hi,

I have been trying to use this rubygem along with Dovecot to mark messages as 'Forwarded'. Annoyingly it doesn't seem to use the 'Passed' / `P` flag:

[Defined by DJB](http://cr.yp.to/proto/maildir.html) as:
> Flag "P" (passed): the user has resent/forwarded/bounced this message to someone else

But instead uses the 'IMAP keywords' mapped to lowercase flags. This is defined here:
https://wiki2.dovecot.org/MailboxFormat/Maildir

[Wikipedia](https://en.wikipedia.org/wiki/Maildir#Technical_operation) says:
> Dovecot uses lowercase letters to match 26 IMAP keywords, which may include standardised keywords, such as $MDNSent, and user defined flags.

The contents of my `~/Maildir/dovecot-keywords` is:
```
0 $NotJunk
1 $Junk
2 JunkRecorded
3 $Forwarded
4 $MDNSent
```

Thus the flags on a forwarded email is (Seen and Forwarded):
```
1557157086.H228766P2596.lucius.aelius.com:2,Sd
```

Do you think it would be reasonable for this ruby gem to add support for dovecot style IMAP keywords?

Thanks,

nick.

**Comment by todd-a-jacobs** [comment]
Hi, @njh. The current gem uses [(P)assed](https://github.com/ktheory/maildir/blob/master/lib/maildir/message.rb#L104) because it was designed as for the maildir specification, not as an IMAP extensions gem. That said, I'd certainly be open to a pull request that added IMAP keywords in a way that didn't conflict with the core maildir keywords. Such a pull request would definitely need to include tests that show a lack of regressions in that regard.

If you're willing to submit such a pull request, I'd be glad to review it for inclusion. It would definitely make the gem more widely applicable, so I have no objections to extensions so long as they don't conflict with the core mission of supporting the maildir standard.

**Comment by njh** [comment]
Thanks for your speedy response.

I have been thinking about what the API would look like and I was thinking something like this:

Add a keyword (checks `dovecot-keywords` and `calls add_flag('d')` ):

    message.add_dovecot_keyword("$Forwarded") 

Remove a keyword (Checks `dovecot-keywords` and calls `remove_flag('d')` )

    message.remove_dovecot_keyword("$Forwarded")

I am not sure if the keyword doesn't exist, it should add it to `dovecot-keywords` or throw an exception. Although more work, I suspect the former.

**Comment by todd-a-jacobs** [comment]
I'm a little leery of tying the gem to a specific non-standard implementation. From my reading of the code (it's been a while) the gem adds and removes only flags that are defined in the standard, but I don't think it munges non-standard flags. I could be wrong; this is something that would need to be tested.

However, the gem shouldn't really have to know anything about non-maildir flags. It might be worthwhile to simply have a flag like `-e` for extended flags, which turns off the check for inclusion in FLAG_NAMES. The mapping to non-standard flags should probably be handled by the MUA, as anything else would either require coupling the implementation or requiring dependency injection for extended operations.

The goal ought to be to enable you to manipulate arbitrary flags if you want to. Having to depend on Dovecot-specific stuff would then require thinking about other MUAs, too, which probably have their own mapping scheme, files, and mechanisms. The current system ought to work fine with #add_flag and #remove_flag if you loosen up the #include? checks.

**Comment by njh** [comment]
I understand your concerns.

It is unfortunate that Dovecot has its own special way of doing it - rather than there being a standard for storing IMAP keywords / flags in Maildirs. I guess the fact that Maildir isn't part of any standard organisation doesn't help.

One option would be to create a new `dovecot-maildir` ruby gem that subclasses the `maildir` gem but I don't think that would currently be very straightforward.

I will close this issue and try and work out a different solution.
