### ISSUE TITLE
maildir 2.2.2 exists here as a Git tag, but not on rubygems.org

### ISSUE THREAD

**Issue by olleolleolle** [ktheory/maildir#28]
Hi!

I was looking for a line of code, which was fixed in 2015. "Ah, great a fix is in!"

But then I looked at the rubygems.org page for maildir, and I saw that 2.2.1 was the latest published there, so users don't get the benefit of https://github.com/ktheory/maildir/pull/21.

**Comment by ktheory** [comment]
@olleolleolle Just published it! https://rubygems.org/gems/maildir/versions/2.2.2

thx for the nudge.

**Comment by ioquatix** [comment]
Nice work!
