### ISSUE TITLE
Gem is missing activesupport dependency

### ISSUE THREAD

**Issue by tmilker** [ktheory/maildir#29]
The gemspec doesn't define a dependency on activesupport, which causes require 'maildir' to fail.  This  appears to have been introduced with commit 0f9c2f481c37b97879f285280e3ba5f3e0dc51fe

**Comment by todd-a-jacobs** [comment]
At first glance, this looks like an undeclared development dependency, and shouldn't be causing failures in standard usage. Are you actually seeing non-development dependency failures of some sort?

**Comment by tmilker** [comment]
I just installed the gem with bundle, required it in irb and get the failure when I try to use it.

**Comment by graaff** [comment]
activesupport is required unconditionally in lib/maildir/message.rb so anything using Maildir::Message is going to need that. It looks like it is needed for a single blank? method. Perhaps drop activesupport and use empty? || nil? instead?

**Comment by todd-a-jacobs** [comment]
Version 2.2.3 has been tagged and published.
